name: Build Xenity Engine

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Editor
      run: msbuild Xenity_Engibe.sln /p:Configuration="Release Editor" /p:Platform=x64 /v:minimal

    - name: Find EXE
      run: dir /s /b *.exe

    - name: Zip Output
      run: powershell Compress-Archive -Path **\Release* -DestinationPath xenity_build.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: xenity-build
        path: xenity_build.zip